### ISSUE TITLE
[kobo] porting progress

### ISSUE THREAD

**Issue by raisjn** [mrichards42/remarkable_puzzles#15]
i'm trying to port this to kobo libra (hurrah!), but i'm only seeing a black box where the game usually is. do you have any debugging tips? 

https://imgur.com/a/VmHYQOI is what i'm seeing.

what i've done:

* i'm using the kobo branch of rmkit (under development)
* i added -static and -static-libstdc++ flags to the Makefile (kobo has incompatible versions of libstdc++ and libm)
* ~~i updated all references in fb->width and fb->height to refer to fb->stride, fb->display_width and fb->display_height~~
* i compiled with -DKOBO (instead of -DREMARKABLE).
* i copied over config/ and icons/ to /opt/etc/puzzles/ config, i made /opt/etc/puzzles/save. ~~i can see all of the UI elements, just not the actual game play area. ~~
* ~~if i click in the game play area, the UI does update (for example, i would see "balls marked 1/5" in black box) but i only see a black area where the ST puzzles output should be~~

~~i have a feeling i may have messed up something in rmkit.h in the kobo branch, so i will explore that possibility, too~~

**Comment by raisjn** [comment]
it seems to work now - not sure what i changed in rmkit.h to fix but i'm excited!

**Comment by raisjn** [comment]
some screenshots from kobo libra h20: 
![20220103_112520](https://user-images.githubusercontent.com/70462544/147972033-f06ad175-06ee-4132-951f-8c4812b9bdcd.jpg)
![20220103_112414](https://user-images.githubusercontent.com/70462544/147972035-4728a421-2a44-471c-8ef1-889d0fff82f2.jpg)

**Comment by raisjn** [comment]
Makefile adjustments to get it working: (using kobo branch of rmkit-dev/rmkit). No changes necessary to remarkable_puzzles code, although I haven't been able to generate the icons myself yet (likely due to me breaking rmkit.h's FileFB or VirtualFB somehow for the icon generating use case)

```
diff --git a/Makefile b/Makefile
index b0367e4..d207df4 100644
--- a/Makefile
+++ b/Makefile
@@ -29,7 +29,7 @@ resim: default
 
 
 #### rmkit
-RMKIT_FLAGS = -D"REMARKABLE=1" \
+RMKIT_FLAGS = -D"KOBO=1" -D"RMKIT_IMPLEMENTATION" \
 	-pthread -lpthread
 
 $(BUILD_DIR)/rmkit.h:
@@ -55,6 +55,7 @@ INCLUDES  = -I./ -Isrc/ -Ivendor/inih -Ivendor/puzzles
 INCLUDES += -isystem $(BUILD_DIR)/
 
 CXXFLAGS  = -Wall $(INCLUDES) $(RMKIT_FLAGS) $(BUILD_FLAGS)
+CXXFLAGS += -static -static-libstdc++ -static-libgcc
 CXXFLAGS += -fdata-sections -ffunction-sections -Wl,--gc-sections
 CXXFLAGS += -D'RMP_COMPILE_DATE="$(RMP_COMPILE_DATE)"'
 ifneq ($(strip $(RMP_VERSION)),)
```

**Comment by mrichards42** [comment]
Cool!! Happy to take a patch to add those flags only for kobo (or well, I assume `-D"RMKIT_IMPLEMENTATION"` is the new way to do things across the board?)

**Comment by raisjn** [comment]
yeah, `-DRMKIT_IMPLEMENTATION` is required for builds now (i'm slowly trying to make it possible to include rmkit.h from multiple .h files like a normal cpp project). -DREMARKABLE and -DKOBO are for (rm1, rm2) and (kobo libra) respectively. i haven't merged kobo branch into master yet, still auditing and improving things before i squash it in. i'll ping when i merge into master 

i figured out why the icons weren't building: i had to scp save/* over to /opt/etc/puzzle-icons/ and now i can run the icon building binary successfully. so all's well :-D i did notice that unruly doesn't have a save file, though (and causes a crash, it seems)
