### ISSUE TITLE
build on main?

### ISSUE THREAD

**Issue by raisjn** [mrichards42/remarkable_puzzles#3]
does clean checkout of main build properly? looks like MAIN_SRCS should be MAIN_SRC but even then, i still have trouble building. is it possible the src files are being concatenated in wrong order or something similar?

<details>
<pre>
docker run \
        -v "/home/okay/tonka/apps/remarkable/remarkable_puzzles:/home/okay/tonka/apps/remarkable/remarkable_puzzles" -w "/home/okay/tonka/apps/remarkable/remarkable_puzzles" \
        -e ARCH -e BUILD -e BUILD_ROOT -e BUILD_DIR \
        --rm remarkable_puzzles_toolchain:latest \
        make puzzles  -r
rm build/release/main.cpp || true
rm: cannot remove 'build/release/main.cpp': No such file or directory
for f in src/puzzles.cpp src/main.cpp src/ui/puzzle_drawer.cpp src/ui/canvas.cpp; do echo "#include \"$f\"" >> build/release/main.cpp; done
arm-linux-gnueabihf-g++ -Wall -I./ -Isrc/ -isystem build/release/ -D"REMARKABLE=1" -pthread -lpthread -O2 -DNDEBUG -fdata-sections -ffunction-sections -Wl,--gc-sections -MMD -MP -c -o build/release/main.o build/release/main.cpp
In file included from /opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/vector:60,
                 from /home/okay/tonka/apps/remarkable/remarkable_puzzles/vendor/rmkit/src/rmkit/util/signals.cpy,
                 from ./src/main.cpp:5,
                 from build/release/main.cpp:2:
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/bits/stl_algobase.h:243:56: error: macro "min" passed 3 arguments, but takes just 2
     min(const _Tp& __a, const _Tp& __b, _Compare __comp)
                                                        ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/bits/stl_algobase.h:265:56: error: macro "max" passed 3 arguments, but takes just 2
     max(const _Tp& __a, const _Tp& __b, _Compare __comp)
                                                        ^
In file included from /opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/chrono:40,
                 from /home/okay/tonka/apps/remarkable/remarkable_puzzles/vendor/rmkit/src/shared/clockwatch.cpy:3,
                 from ./src/main.cpp:5,
                 from build/release/main.cpp:2:
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/limits:317:11: error: macro "min" requires 2 arguments, but only 1 given
       min() _GLIBCXX_USE_NOEXCEPT { return _Tp(); }
           ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/limits:321:11: error: macro "max" requires 2 arguments, but only 1 given
       max() _GLIBCXX_USE_NOEXCEPT { return _Tp(); }
           ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/limits:388:11: error: macro "min" requires 2 arguments, but only 1 given
       min() _GLIBCXX_USE_NOEXCEPT { return false; }
           ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/limits:391:11: error: macro "max" requires 2 arguments, but only 1 given
       max() _GLIBCXX_USE_NOEXCEPT { return true; }
           ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/limits:395:38: error: macro "min" requires 2 arguments, but only 1 given
       lowest() noexcept { return min(); }
                                      ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/limits:457:11: error: macro "min" requires 2 arguments, but only 1 given
       min() _GLIBCXX_USE_NOEXCEPT { return __glibcxx_min(char); }
           ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/limits:460:11: error: macro "max" requires 2 arguments, but only 1 given
       max() _GLIBCXX_USE_NOEXCEPT { return __glibcxx_max(char); }
           ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/limits:464:38: error: macro "min" requires 2 arguments, but only 1 given
       lowest() noexcept { return min(); }
                                      ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/limits:524:11: error: macro "min" requires 2 arguments, but only 1 given
       min() _GLIBCXX_USE_NOEXCEPT { return -__SCHAR_MAX__ - 1; }
           ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/limits:527:11: error: macro "max" requires 2 arguments, but only 1 given
       max() _GLIBCXX_USE_NOEXCEPT { return __SCHAR_MAX__; }
           ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/limits:531:38: error: macro "min" requires 2 arguments, but only 1 given
       lowest() noexcept { return min(); }
                                      ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/limits:594:11: error: macro "min" requires 2 arguments, but only 1 given
       min() _GLIBCXX_USE_NOEXCEPT { return 0; }
           ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/limits:597:11: error: macro "max" requires 2 arguments, but only 1 given
       max() _GLIBCXX_USE_NOEXCEPT { return __SCHAR_MAX__ * 2U + 1; }
           ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/limits:601:38: error: macro "min" requires 2 arguments, but only 1 given
       lowest() noexcept { return min(); }
                                      ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/limits:667:11: error: macro "min" requires 2 arguments, but only 1 given
       min() _GLIBCXX_USE_NOEXCEPT { return __glibcxx_min (wchar_t); }
           ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/limits:670:11: error: macro "max" requires 2 arguments, but only 1 given
       max() _GLIBCXX_USE_NOEXCEPT { return __glibcxx_max (wchar_t); }
           ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/limits:674:38: error: macro "min" requires 2 arguments, but only 1 given
       lowest() noexcept { return min(); }
                                      ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/limits:736:11: error: macro "min" requires 2 arguments, but only 1 given
       min() noexcept { return __glibcxx_min (char16_t); }
           ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/limits:739:11: error: macro "max" requires 2 arguments, but only 1 given
       max() noexcept { return __glibcxx_max (char16_t); }
           ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/limits:742:38: error: macro "min" requires 2 arguments, but only 1 given
       lowest() noexcept { return min(); }
                                      ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/limits:797:11: error: macro "min" requires 2 arguments, but only 1 given
       min() noexcept { return __glibcxx_min (char32_t); }
           ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/limits:800:11: error: macro "max" requires 2 arguments, but only 1 given
       max() noexcept { return __glibcxx_max (char32_t); }
           ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/limits:803:38: error: macro "min" requires 2 arguments, but only 1 given
       lowest() noexcept { return min(); }
                                      ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/limits:859:11: error: macro "min" requires 2 arguments, but only 1 given
       min() _GLIBCXX_USE_NOEXCEPT { return -__SHRT_MAX__ - 1; }
           ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/limits:862:11: error: macro "max" requires 2 arguments, but only 1 given
       max() _GLIBCXX_USE_NOEXCEPT { return __SHRT_MAX__; }
           ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/limits:866:38: error: macro "min" requires 2 arguments, but only 1 given
       lowest() noexcept { return min(); }
                                      ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/limits:926:11: error: macro "min" requires 2 arguments, but only 1 given
       min() _GLIBCXX_USE_NOEXCEPT { return 0; }
           ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/limits:929:11: error: macro "max" requires 2 arguments, but only 1 given
       max() _GLIBCXX_USE_NOEXCEPT { return __SHRT_MAX__ * 2U + 1; }
           ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/limits:933:38: error: macro "min" requires 2 arguments, but only 1 given
       lowest() noexcept { return min(); }
                                      ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/limits:999:11: error: macro "min" requires 2 arguments, but only 1 given
       min() _GLIBCXX_USE_NOEXCEPT { return -__INT_MAX__ - 1; }
           ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/limits:1002:11: error: macro "max" requires 2 arguments, but only 1 given
       max() _GLIBCXX_USE_NOEXCEPT { return __INT_MAX__; }
           ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/limits:1006:38: error: macro "min" requires 2 arguments, but only 1 given
       lowest() noexcept { return min(); }
                                      ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/limits:1066:11: error: macro "min" requires 2 arguments, but only 1 given
       min() _GLIBCXX_USE_NOEXCEPT { return 0; }
           ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/limits:1069:11: error: macro "max" requires 2 arguments, but only 1 given
       max() _GLIBCXX_USE_NOEXCEPT { return __INT_MAX__ * 2U + 1; }
           ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/limits:1073:38: error: macro "min" requires 2 arguments, but only 1 given
       lowest() noexcept { return min(); }
                                      ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/limits:1138:11: error: macro "min" requires 2 arguments, but only 1 given
       min() _GLIBCXX_USE_NOEXCEPT { return -__LONG_MAX__ - 1; }
           ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/limits:1141:11: error: macro "max" requires 2 arguments, but only 1 given
       max() _GLIBCXX_USE_NOEXCEPT { return __LONG_MAX__; }
           ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/limits:1145:38: error: macro "min" requires 2 arguments, but only 1 given
       lowest() noexcept { return min(); }
                                      ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/limits:1205:11: error: macro "min" requires 2 arguments, but only 1 given
       min() _GLIBCXX_USE_NOEXCEPT { return 0; }
           ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/limits:1208:11: error: macro "max" requires 2 arguments, but only 1 given
       max() _GLIBCXX_USE_NOEXCEPT { return __LONG_MAX__ * 2UL + 1; }
           ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/limits:1212:38: error: macro "min" requires 2 arguments, but only 1 given
       lowest() noexcept { return min(); }
                                      ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/limits:1278:11: error: macro "min" requires 2 arguments, but only 1 given
       min() _GLIBCXX_USE_NOEXCEPT { return -__LONG_LONG_MAX__ - 1; }
           ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/limits:1281:11: error: macro "max" requires 2 arguments, but only 1 given
       max() _GLIBCXX_USE_NOEXCEPT { return __LONG_LONG_MAX__; }
           ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/limits:1285:38: error: macro "min" requires 2 arguments, but only 1 given
       lowest() noexcept { return min(); }
                                      ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/limits:1348:11: error: macro "min" requires 2 arguments, but only 1 given
       min() _GLIBCXX_USE_NOEXCEPT { return 0; }
           ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/limits:1351:11: error: macro "max" requires 2 arguments, but only 1 given
       max() _GLIBCXX_USE_NOEXCEPT { return __LONG_LONG_MAX__ * 2ULL + 1; }
           ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/limits:1355:38: error: macro "min" requires 2 arguments, but only 1 given
       lowest() noexcept { return min(); }
                                      ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/limits:1599:11: error: macro "min" requires 2 arguments, but only 1 given
       min() _GLIBCXX_USE_NOEXCEPT { return __FLT_MIN__; }
           ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/limits:1602:11: error: macro "max" requires 2 arguments, but only 1 given
       max() _GLIBCXX_USE_NOEXCEPT { return __FLT_MAX__; }
           ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/limits:1674:11: error: macro "min" requires 2 arguments, but only 1 given
       min() _GLIBCXX_USE_NOEXCEPT { return __DBL_MIN__; }
           ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/limits:1677:11: error: macro "max" requires 2 arguments, but only 1 given
       max() _GLIBCXX_USE_NOEXCEPT { return __DBL_MAX__; }
           ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/limits:1749:11: error: macro "min" requires 2 arguments, but only 1 given
       min() _GLIBCXX_USE_NOEXCEPT { return __LDBL_MIN__; }
           ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/limits:1752:11: error: macro "max" requires 2 arguments, but only 1 given
       max() _GLIBCXX_USE_NOEXCEPT { return __LDBL_MAX__; }
           ^
In file included from /opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/chrono:42,
                 from /home/okay/tonka/apps/remarkable/remarkable_puzzles/vendor/rmkit/src/shared/clockwatch.cpy:3,
                 from ./src/main.cpp:5,
                 from build/release/main.cpp:2:
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/bits/parse_numbers.h:268:65: error: macro "max" requires 2 arguments, but only 1 given
     : conditional_t<(_Val <= std::numeric_limits<_IntType>::max()),
                                                                 ^
In file included from /home/okay/tonka/apps/remarkable/remarkable_puzzles/vendor/rmkit/src/shared/clockwatch.cpy:3,
                 from ./src/main.cpp:5,
                 from build/release/main.cpp:2:
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/chrono:282:6: error: macro "max" requires 2 arguments, but only 1 given
  max() noexcept
      ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/chrono:283:37: error: macro "max" requires 2 arguments, but only 1 given
  { return numeric_limits<_Rep>::max(); }
                                     ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/chrono:286:6: error: macro "min" requires 2 arguments, but only 1 given
  min() noexcept
      ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/chrono:437:6: error: macro "min" requires 2 arguments, but only 1 given
  min() noexcept
      ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/chrono:438:46: error: macro "min" requires 2 arguments, but only 1 given
  { return duration(duration_values<rep>::min()); }
                                              ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/chrono:441:6: error: macro "max" requires 2 arguments, but only 1 given
  max() noexcept
      ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/chrono:442:46: error: macro "max" requires 2 arguments, but only 1 given
  { return duration(duration_values<rep>::max()); }
                                              ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/chrono:659:6: error: macro "min" requires 2 arguments, but only 1 given
  min() noexcept
      ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/chrono:660:36: error: macro "min" requires 2 arguments, but only 1 given
  { return time_point(duration::min()); }
                                    ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/chrono:663:6: error: macro "max" requires 2 arguments, but only 1 given
  max() noexcept
      ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/chrono:664:36: error: macro "max" requires 2 arguments, but only 1 given
  { return time_point(duration::max()); }
                                    ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/chrono:825:49: error: macro "min" requires 2 arguments, but only 1 given
       static_assert(system_clock::duration::min()
                                                 ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/chrono:923:37: error: macro "min" requires 2 arguments, but only 1 given
     operator""min(long double __mins)
                                     ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/chrono:928:21: error: macro "min" requires 2 arguments, but only 1 given
       operator""min()
                     ^
In file included from ./src/main.cpp:5,
                 from build/release/main.cpp:2:
/home/okay/tonka/apps/remarkable/remarkable_puzzles/vendor/rmkit/src/rmkit/input/device_id.cpy: In function 'input::EV_TYPE input::id_by_name(int)':
/home/okay/tonka/apps/remarkable/remarkable_puzzles/vendor/rmkit/src/rmkit/input/device_id.cpy:59:19: error: 'string' is not a member of 'std'
     s := std::string(name)
                   ^~~~~~
/home/okay/tonka/apps/remarkable/remarkable_puzzles/vendor/rmkit/src/rmkit/input/device_id.cpy:59:19: note: 'std::string' is defined in header '<string>'; did you forget to '#include <string>'?
/home/okay/tonka/apps/remarkable/remarkable_puzzles/vendor/rmkit/src/rmkit/input/device_id.cpy:7:1:
+#include <string>

/home/okay/tonka/apps/remarkable/remarkable_puzzles/vendor/rmkit/src/rmkit/input/device_id.cpy:59:19:
     s := std::string(name)
                   ^~~~~~
In file included from ./src/puzzles.hpp:19,
                 from ./src/puzzles.cpp:7,
                 from build/release/main.cpp:1:
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/bits/stl_algobase.h: At global scope:
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/bits/stl_algobase.h:195:5: error: expected unqualified-id before 'const'
     min(const _Tp& __a, const _Tp& __b)
     ^~~
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/bits/stl_algobase.h:195:5: error: expected ')' before 'const'
./vendor/puzzles/puzzles.h:26:20: note: to match this '('
 #define min(x,y) ( (x)<(y) ? (x) : (y) )
                    ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/bits/stl_algobase.h:195:5: error: expected ')' before 'const'
     min(const _Tp& __a, const _Tp& __b)
     ^~~
./vendor/puzzles/puzzles.h:26:18: note: to match this '('
 #define min(x,y) ( (x)<(y) ? (x) : (y) )
                  ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/bits/stl_algobase.h:219:5: error: expected unqualified-id before 'const'
     max(const _Tp& __a, const _Tp& __b)
     ^~~
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/bits/stl_algobase.h:219:5: error: expected ')' before 'const'
./vendor/puzzles/puzzles.h:23:20: note: to match this '('
 #define max(x,y) ( (x)>(y) ? (x) : (y) )
                    ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/bits/stl_algobase.h:219:5: error: expected ')' before 'const'
     max(const _Tp& __a, const _Tp& __b)
     ^~~
./vendor/puzzles/puzzles.h:23:18: note: to match this '('
 #define max(x,y) ( (x)>(y) ? (x) : (y) )
                  ^
In file included from /opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/vector:60,
                 from /home/okay/tonka/apps/remarkable/remarkable_puzzles/vendor/rmkit/src/rmkit/util/signals.cpy,
                 from ./src/main.cpp:5,
                 from build/release/main.cpp:2:
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/bits/stl_algobase.h:246:7: error: expected primary-expression before 'if'
       if (__comp(__b, __a))
       ^~
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/bits/stl_algobase.h:246:7: error: expected '}' before 'if'
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/bits/stl_algobase.h:244:5: note: to match this '{'
     {
     ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/bits/stl_algobase.h:244:6: error: expected ';' before 'if'
     {
      ^
      ;
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/bits/stl_algobase.h:246:7:
       if (__comp(__b, __a))
       ~~
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/bits/stl_algobase.h:248:7: error: expected unqualified-id before 'return'
       return __a;
       ^~~~~~
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/bits/stl_algobase.h:268:7: error: expected primary-expression before 'if'
       if (__comp(__a, __b))
       ^~
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/bits/stl_algobase.h:268:7: error: expected '}' before 'if'
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/bits/stl_algobase.h:266:5: note: to match this '{'
     {
     ^
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/bits/stl_algobase.h:266:6: error: expected ';' before 'if'
     {
      ^
      ;
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/bits/stl_algobase.h:268:7:
       if (__comp(__a, __b))
       ~~
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/bits/stl_algobase.h:270:7: error: expected unqualified-id before 'return'
       return __a;
       ^~~~~~
/opt/x-tools/arm-remarkable-linux-gnueabihf/arm-remarkable-linux-gnueabihf/include/c++/8.3.0/bits/stl_algobase.h:271:5: error: expected declaration before '}' token
     }
     ^
make: *** [Makefile:55: build/release/main.o] Error 1
make: *** [Makefile:77: docker] Error 2

</pre>
</details>

**Comment by mrichards42** [comment]
Oops, good catch on MAIN_SRCS. I also changed the rm command since I see it's erroring. Hopefully fixed in 6abf98839478a95751d572708f283ac357ef1562, but I haven't seen the errors from the system headers before, and it builds fine for me now.

**Comment by raisjn** [comment]
I did `echo $(SRCS)` and got `echo src/puzzles.cpp src/main.cpp src/ui/puzzle_drawer.cpp src/ui/canvas.cpp` - is it similar order for you? i ran find command and they always come out in that order

**Comment by mrichards42** [comment]
Ah, I can reproduce now. I was always getting this order: `echo src/main.cpp src/puzzles.cpp src/ui/canvas.cpp src/ui/puzzle_drawer.cpp`. I'll dig into this more.

**Comment by mrichards42** [comment]
Ok, this should do it: 254fb84a53e256afe79f07d1cc0636194133141d. puzzles.h (C) defines min and max as macros, so the STL complains when `using std;` with `<algorithm>`.

**Comment by raisjn** [comment]
compiled and works for me - was just catching up on the commit log and changes, looks great! i notice that the UI isn't redrawing well (when swapping games, etc) - not sure if its the WAVEFORM_MODE or if it is an issue with rm2fb. 

also - is a right click expected? how can that be added?

**Comment by mrichards42** [comment]
> i notice that the UI isn't redrawing well (when swapping games, etc) - not sure if its the WAVEFORM_MODE or if it is an issue with rm2fb.

Yeah, not totally sure. I added an unconditional full memcpy in `Canvas::render()` to get around the overlay problems. I also added a full screen clear in `App::start_game()` b/c I was getting all kinds of weird remnants from previous games. Might have something to do with it, or waveform mode could be it as well. It might take defining custom colors per game to get drawing to be reasonable, not sure.

> also - is a right click expected? how can that be added?

Ah yeah, I haven't done that yet :) The android port uses a long press to simulate right click, and has a toggle button that lets you switch long and short presses. I figure long press is a good solution for now, but what I'd really love to do is sort of character recognition so you can draw on the puzzles. Like there's a sudoku and a kenken clone, and it would be cool to be able to just draw the numbers. Or for loopy or slant, actually drawing the lines on the grid would be neat.

**Comment by raisjn** [comment]
i just tested jumping between apps using remux and they paint correctly, so the WAVEFORM_MODE should be upgraded. 

```
diff --git a/src/ui/canvas.cpp b/src/ui/canvas.cpp
index 4566c28..91cdfc4 100644
--- a/src/ui/canvas.cpp
+++ b/src/ui/canvas.cpp
@@ -72,12 +72,13 @@ void Canvas::render()
 {
     // TODO: merge layers
     // TODO: consider different waveform modes
-    fb->waveform_mode = WAVEFORM_MODE_AUTO;
+    fb->waveform_mode = WAVEFORM_MODE_GC16;
     framebuffer::FB * vfb = drawfb(0);
 
     auto dirty = vfb->dirty_area;
     // TODO: this is necessary for painting after an overlay has been shown. Is
     // there a way to figure out which area is dirty in that situation?
+    this->undraw();
     dirty.x0 = 0;
     dirty.y0 = 0;
     dirty.x1 = vfb->width;
```

but even with this change, i think the canvas is not re-rendering correctly always with certain games. with other games it seems fine. i haven't tested always using GC16
