### ISSUE TITLE
toltec package recipe

### ISSUE THREAD

**Issue by raisjn** [mrichards42/remarkable_puzzles#9]
i started trying to package this for toltec: https://github.com/toltec-dev/toltec/compare/testing...rmkit-dev:testing (it shows up in our toltec test repo as https://opkg.rmkit.dev/testing/st_puzzles_0.0.1-1_armv7-3.2.ipk)

it's missing:

* icon
* name
* maintainer
* correct version string
* etc

but just want to leave this artifact around for when you are ready to release

**Comment by mrichards42** [comment]
This is awesome, thanks for getting that started!

**Comment by mrichards42** [comment]
@raisjn re: the toltec package you've been working on, I have to [look this up](https://git-scm.com/book/en/v2/Git-Tools-Submodules#_cloning_submodules) any time I clone something with submodules, but I think you can fetch them both with one line:

```sh
git submodule update --init --recursive
# or to get a shallow clone
git submodule update --init --recursive --depth 1
```

**Comment by raisjn** [comment]
the zip doesn't come with the git submodule info afaik. are you able to build pkg with that? (make st_puzzles)

**Comment by raisjn** [comment]
oh, right. it isn't a repo, so git sub module fails. but it does come with the module info

**Comment by mrichards42** [comment]
oh I follow, that is super obnoxious. it comes with the module info, but not the sha

**Comment by mrichards42** [comment]
maybe the thing to do is tag releases and have a github action that builds a zip instead of using the automatically generated zip? or have you talked about using shallow clones in recipes instead of zip files over in toltec?

**Comment by raisjn** [comment]
> maybe the thing to do is tag releases and have a github action that builds a zip instead of using the automatically generated zip? 

seems fine to me, maybe a bit of extra work but definitely better than putting up pre-compiled binaries

> or have you talked about using shallow clones in recipes instead of zip files over in toltec?

its a topic to revisit for repositories with submodules if you want to open issue in toltec repo. this also came up when i wanted to build koreader (because it has submodules, iirc) and we can't change koreader. we are using the koreader pre-compiled release build for now. 

i think the thing with zip is that its easy to verify hash. but i don't think people trust that the retrieved branch / commit from a shallow clone is secure. 

matteo recently re-wrote the tooling to python, so it should be easy enough to support git repos

**Comment by raisjn** [comment]
i added you to rmkit-dev/toltec, if you want to push fixes / adjustments. it will get auto-built when testing is updated (and synced to opkg.rmkit.dev)

**Comment by raisjn** [comment]
also, let me know if you'd like a page on rmkit.dev (with screenshots) for puzzles (vs. just a link out to your repo) - would be pretty easy to add

**Comment by mrichards42** [comment]
yeah, that would be sweet! thanks for the offer

**Comment by raisjn** [comment]
WIP: https://rmkit.dev/apps/puzzles

**Comment by raisjn** [comment]
i bumped the recipe a day ago (adds inih vendor dep) - i thought i saw a commit that makes .zip files through CI - where can i find those?

**Comment by mrichards42** [comment]
Ah yeah -- each commit builds and uploads to Actions as an artifact, but I think those are deleted after 90 days, so not a permanent solution. The last build is https://github.com/mrichards42/remarkable_puzzles/actions/runs/619708150

I also have it set up to copy the source zip when a release is made -- I'm going to tag 0.1.0 to get that set up. Still a bit to do to feel like this is ready to send out into the world, but might as well get the fully zipped source up to make packaging easier.

**Comment by mrichards42** [comment]
... and here's a permanent version of the source for 0.1.0: https://github.com/mrichards42/remarkable_puzzles/releases/download/v0.1.0/puzzles-source.tar.gz

**Comment by raisjn** [comment]
great, i updated the recipe - much simpler now

one thing is the patch having to add sstream include in one of the files

**Comment by mrichards42** [comment]
oops, good catch, fixed

**Comment by mrichards42** [comment]
Alright, I think v0.2.2 is a good first toltec release. I just need to make an icon.

I saw your toltect-dev branch calls the package `st_puzzles`, which 🤷 I don't really care what the binary or package is called (st_puzzles is fine, puzzle_collection, just puzzles, whatever), but it seems like the /opt/etc/... directory structure should use the same name as the binary. Does `puzzles` feel like a too generic name for the binary? I'm happy to make the directory configurable in the Makefile.

**Comment by raisjn** [comment]
at first i thought puzzles is too generic, but i think simon tatham may have earned it at this point. i'll update it to 'puzzles', we'll see what other maintainers think

**Comment by raisjn** [comment]
i'll finish this recipe tomorrow / this weekend and submit it to toltec

**Comment by raisjn** [comment]
https://github.com/toltec-dev/toltec/pull/326 is the PR

**Comment by mrichards42** [comment]
Awesome, thanks! No worries on the timing, I got the 2.6 upgrade, and I've just been waiting for things to settle down before getting back into puzzle dev.

**Comment by Eeems** [comment]
@mrichards42 Now that we're at 2.8 and 2.9 is just starting to roll out, things have settled down in the testing branch for toltec, but we are still figuring out how to deliver that to stable due to a large change that happened. Are you expecting to get back into development any time soon? I'd at least recommend getting an icon added as it's fairly straight forward and always looks nice :)

**Comment by mrichards42** [comment]
@Eeems it's been about a month since your comment so I suppose clearly I haven't had a ton of time recently :) I'm definitely looking to do a little more work on this at some point, including the icon, so the project certainly isn't dead. And I saw that toltec had a stable release recently, which is encouraging!

**Comment by Eeems** [comment]
@mrichards42 totally understandable. Yes, toltec had a stable merge and now supports 2.8. the 2.9 merge is underway.
